version: "3.4"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    ports:
      - 8000:8000
    command:
      - npm run dev